// <auto-generated />
namespace TheatreCMS3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddJoinedAndLeft : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddJoinedAndLeft));
        
        string IMigrationMetadata.Id
        {
            get { return "202603010317048_AddJoinedAndLeft"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
